# Aplicação alvo — Parabank (sistema bancário público para treino)
base.url=https://parabank.parasoft.com

# Navegador: chrome | firefox
browser=chrome
headless=false

# Banco de Dados (PostgreSQL local via Docker)
# Para DB2 real, trocar por: jdbc:db2://host:50000/BANKING
db.url=jdbc:postgresql://localhost:5432/banking_db
db.user=qa_user
db.password=qa_password
